# Generated by Django 5.0.2 on 2024-02-24 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='volume',
            field=models.DecimalField(decimal_places=1, max_digits=1),
        ),
    ]
