# Generated by Django 5.0.2 on 2024-02-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_alter_drink_volume'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drink',
            name='volume',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
    ]
