# Generated by Django 5.0.2 on 2024-03-17 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0002_foodtype_food_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='foodtype',
            old_name='type',
            new_name='name',
        ),
    ]
