# Generated by Django 5.0.2 on 2024-03-18 00:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_rename_type_foodtype_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.ForeignKey(db_column='TypeFoodTypeRef', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.foodtype', verbose_name='Type'),
        ),
    ]
