# Generated by Django 5.0.2 on 2024-02-24 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_alter_drink_volume'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdrink',
            old_name='quantity',
            new_name='drink_quantity',
        ),
        migrations.RenameField(
            model_name='orderfood',
            old_name='quantity',
            new_name='food_quantity',
        ),
    ]
