# Generated by Django 5.0.2 on 2024-02-24 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0004_rename_quantity_orderdrink_drink_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderdrink',
            old_name='drink_quantity',
            new_name='quantity',
        ),
        migrations.RenameField(
            model_name='orderfood',
            old_name='food_quantity',
            new_name='quantity',
        ),
    ]
