# Generated by Django 5.0.2 on 2024-02-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0005_rename_drink_quantity_orderdrink_quantity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='photo',
            field=models.ImageField(null=True, upload_to='media\\images'),
        ),
        migrations.AddField(
            model_name='food',
            name='photo',
            field=models.ImageField(null=True, upload_to='media\\images'),
        ),
    ]
