# Generated by Django 5.0.2 on 2024-04-01 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='time',
            field=models.DateTimeField(auto_created=True, auto_now=True, null=True),
        ),
    ]
