# Generated by Django 5.0.2 on 2024-03-18 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_remove_cart_product_id_remove_cart_product_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cart_items',
            field=models.ManyToManyField(related_name='orders', to='cart.cart'),
        ),
    ]
