# Generated by Django 5.0.2 on 2024-03-20 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_remove_order_cart_items_remove_product_content_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drinkcart',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='foodcart',
            name='session_key',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
