# Generated by Django 5.0.2 on 2024-03-20 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_drinkcart_session_key_foodcart_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkcart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
