# Generated by Django 5.0.2 on 2024-03-20 21:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_drinkcart_quantity_alter_foodcart_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkcart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.order'),
        ),
        migrations.AlterField(
            model_name='drinkcart',
            name='quantity',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.order'),
        ),
        migrations.AlterField(
            model_name='foodcart',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
