# Generated by Django 5.0.2 on 2024-03-20 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_drinkcart_order_alter_drinkcart_quantity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkcart',
            old_name='drink',
            new_name='drinks',
        ),
        migrations.RenameField(
            model_name='foodcart',
            old_name='food',
            new_name='foods',
        ),
    ]
