# Generated by Django 5.0.2 on 2024-03-20 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_rename_drink_drinkcart_drinks_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkcart',
            old_name='drinks',
            new_name='drink',
        ),
        migrations.RenameField(
            model_name='foodcart',
            old_name='foods',
            new_name='food',
        ),
    ]
