# Generated by Django 5.0.2 on 2024-03-21 14:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0014_rename_drinks_drinkcart_drink_and_more'),
        ('delivery', '0005_alter_food_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkcart',
            name='drink',
        ),
        migrations.RemoveField(
            model_name='drinkcart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='drinkcart',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='foodcart',
            name='food',
        ),
        migrations.RemoveField(
            model_name='foodcart',
            name='price',
        ),
        migrations.RemoveField(
            model_name='foodcart',
            name='quantity',
        ),
        migrations.CreateModel(
            name='DrinkCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('drink', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.drink')),
                ('drink_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.drinkcart')),
            ],
        ),
        migrations.AddField(
            model_name='drinkcart',
            name='drinks',
            field=models.ManyToManyField(through='cart.DrinkCartItem', to='delivery.drink'),
        ),
        migrations.CreateModel(
            name='FoodCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('food', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.food')),
                ('food_cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cart.foodcart')),
            ],
        ),
        migrations.AddField(
            model_name='foodcart',
            name='foods',
            field=models.ManyToManyField(through='cart.FoodCartItem', to='delivery.food'),
        ),
    ]
