# Generated by Django 5.0.2 on 2024-03-21 19:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0015_remove_drinkcart_drink_remove_drinkcart_price_and_more'),
        ('delivery', '0005_alter_food_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkcartitem',
            name='drink',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.drink'),
        ),
        migrations.AlterField(
            model_name='drinkcartitem',
            name='drink_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.drinkcart'),
        ),
        migrations.AlterField(
            model_name='foodcartitem',
            name='food',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='delivery.food'),
        ),
        migrations.AlterField(
            model_name='foodcartitem',
            name='food_cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='cart.foodcart'),
        ),
    ]
