# Generated by Django 5.0.2 on 2024-03-21 23:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0016_alter_drinkcartitem_drink_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='drinkcart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='foodcart',
            name='order',
        ),
        migrations.AddField(
            model_name='drinkcartitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.order'),
        ),
        migrations.AddField(
            model_name='foodcartitem',
            name='order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='cart.order'),
        ),
    ]
