# Generated by Django 5.0.2 on 2024-03-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0019_alter_order_phone_number'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='CartOrder',
        ),
    ]
